apiVersion: v1
kind: Service
metadata:
  name: odamc-webhook
spec:
  clusterIP: None
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
    nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: odamc-webhook
subsets:
- addresses:
  - ip: 10.8.0.18
  ports:
  - name: https
    port: 8080


# ping odamc-webhook.odmac.svc.cluster.local