kind: DeploymentConfig
apiVersion: "v1"
metadata:
  labels:
    app: "chuck-api"
  name: "chuck-api"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/affinity: '{"podAntiAffinity":{"requiredDuringSchedulingIgnoredDuringExecution": [{"labelSelector":{"matchExpressions": [{"key": "zone", "operator": "In", "values":["z1","z2"]}]}, "topologyKey": "kubernetes.io/hostname"}]}}'
      labels:
        app: "chuck-api"
    spec:
      containers:
      - name: "chuck-api"
        image: "dimssss/chuck-api:0.1"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod